name: CI/CD Pre-deployment Checks

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

# Cancel in-progress runs for same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    # Minimal required permissions
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        
      - name: Create mock Amplify config for CI
        run: |
          echo '{
            "aws_project_region": "us-east-1",
            "aws_cognito_region": "us-east-1",
            "aws_user_pools_id": "mock-pool",
            "aws_user_pools_web_client_id": "mock-client"
          }' > amplify_outputs.json
        
      - name: Run pre-commit validation
        run: npm run pre-commit
        env:
          NODE_ENV: production
          
      - name: Validate build output
        run: |
          if [ ! -d ".next" ]; then
            echo "❌ Build failed - .next directory not found"
            exit 1
          fi
          
          if [ ! -f ".next/BUILD_ID" ]; then
            echo "❌ Build failed - BUILD_ID not found"
            exit 1
          fi
          
          echo "✅ Build validation successful"
          echo "📦 Build ID: $(cat .next/BUILD_ID)"